workflow:
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" && $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_COMMIT_BRANCH == "develop"
      when: always
    - if: $CI_COMMIT_TAG =~ /^A./
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never

image:
 name: jamesljeffrey1995/python:0.1.A.1.2
 entrypoint:
 - '/usr/bin/env'
 - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
    - build

build:
  stage: build 
  script:
  - sed -i "s/slackToken/${slackToken}/" main.py
  - python3 main.py 

